
services:
  ecommercedb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U postgres -d catalogdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:management
    hostname: myrabbit
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: unal
      RABBITMQ_DEFAULT_PASS: unal
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enable_plugins
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8080:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"    # Host-machine 6379 portunu container içi 6379 portuna eşliyor
    volumes:
      - redis_data:/data        # Kalıcılık için volume

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."    

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  rabbitmq_data:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  redis_data:
